version: '3'

services:
  frontend:
    build: ./coding_online_web
    ports:
      - "3000:3000"
    networks:
      - app_network
    
  backend:
    build: ./coding_online_api
    ports:
      - "8080:8080"
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge
